tbsgame: main.cpp
	g++ main.cpp button2.cpp picture.cpp tile.cpp camera.cpp piece.cpp -lSDL2 -lSDL2_image -o tbsgame.out
#tbstest: tests.cpp
#	g++ -o the_tests.out tests.cpp button2.cpp picture.cpp tile.cpp camera.cpp helper_functions.cpp -lSDL2 -lSDL2_image -lgtest -lgtest_main