// defaults.h


#ifndef _DEFAULTS_H
#define _DEFAULTS_H

#include "definitions.h"

#define WIDTH 15
const u8 DIAG = (u8) (WIDTH/sqrt(2));
const u8 HEIGHT = WIDTH + 2*DIAG - 2;

#define MAX_STAMINA 10
#define STARTING_STAMINA 10
#define STAMINA_RECHARGE 3
 
#define WHITE_KING_CREATED 1
#define BLACK_KING_CREATED 1
#define WHITE_GUARD_CREATED 4
#define BLACK_GUARD_CREATED 4
#define WHITE_RIFLEMAN_CREATED 8
#define BLACK_RIFLEMAN_CREATED 8
#define WHITE_SPECOPS_CREATED 4
#define BLACK_SPECOPS_CREATED 4
#define WHITE_PARATROOPER_CREATED 4
#define BLACK_PARATROOPER_CREATED 4
#define WHITE_ENGINEER_CREATED 2
#define BLACK_ENGINEER_CREATED 2
#define WHITE_SCOUT_CREATED 2
#define BLACK_SCOUT_CREATED 2
#define WHITE_SEARCHLIGHT_CREATED 1
#define BLACK_SEARCHLIGHT_CREATED 1

const u8 maxWhitePiecesCreated[NUM_PIECE_TYPES] = 
{
	WHITE_KING_CREATED,
	WHITE_GUARD_CREATED,
	WHITE_RIFLEMAN_CREATED,
	WHITE_SPECOPS_CREATED, 
	WHITE_PARATROOPER_CREATED,
	WHITE_ENGINEER_CREATED,
	WHITE_SCOUT_CREATED,
	WHITE_SEARCHLIGHT_CREATED
};

const u8 maxBlackPiecesCreated[NUM_PIECE_TYPES] = 
{
	BLACK_KING_CREATED,
	BLACK_GUARD_CREATED,
	BLACK_RIFLEMAN_CREATED,
	BLACK_SPECOPS_CREATED,
	BLACK_PARATROOPER_CREATED,
	BLACK_ENGINEER_CREATED,
	BLACK_SCOUT_CREATED,
	BLACK_SEARCHLIGHT_CREATED
};

#define KING_STAMINA_DRAIN 1.0f
#define GUARD_STAMINA_DRAIN 3.0f
#define RIFLEMAN_STAMINA_DRAIN 1.0f
#define SPECOPS_STAMINA_DRAIN 2.0f
#define PARATROOPER_STAMINA_DRAIN 2.0f
#define ENGINEER_STAMINA_DRAIN 2.0f
#define SCOUT_STAMINA_DRAIN 1.0f
#define SEARCHLIGHT_STAMINA_DRAIN 255.0f

#define KING_HEALTH_DAMAGE 0
#define GUARD_HEALTH_DAMAGE 0
#define RIFLEMAN_HEALTH_DAMAGE 2
#define SPECOPS_HEALTH_DAMAGE 0
#define PARATROOPER_HEALTH_DAMAGE 0
#define ENGINEER_HEALTH_DAMAGE 0
#define SCOUT_HEALTH_DAMAGE 0
#define SEARCHLIGHT_HEALTH_DAMAGE 0

#define KING_ARMOR_DAMAGE 0
#define GUARD_ARMOR_DAMAGE 0
#define RIFLEMAN_ARMOR_DAMAGE 1
#define SPECOPS_ARMOR_DAMAGE 0
#define PARATROOPER_ARMOR_DAMAGE 0
#define ENGINEER_ARMOR_DAMAGE 0
#define SCOUT_ARMOR_DAMAGE 0
#define SEARCHLIGHT_ARMOR_DAMAGE 0

#define KING_STARTING_HEALTH 1
#define GUARD_STARTING_HEALTH 1
#define RIFLEMAN_STARTING_HEALTH 4
#define SPECOPS_STARTING_HEALTH 1
#define PARATROOPER_STARTING_HEALTH 1
#define ENGINEER_STARTING_HEALTH 1
#define SCOUT_STARTING_HEALTH 1
#define SEARCHLIGHT_STARTING_HEALTH 1

const u8 startingHealth[NUM_PIECE_TYPES] =
{
	KING_STARTING_HEALTH,
	GUARD_STARTING_HEALTH,
	RIFLEMAN_STARTING_HEALTH,
	SPECOPS_STARTING_HEALTH,
	PARATROOPER_STARTING_HEALTH,
	ENGINEER_STARTING_HEALTH,
	SCOUT_STARTING_HEALTH,
	SEARCHLIGHT_STARTING_HEALTH,
};

#define KING_STARTING_ARMOR 0
#define GUARD_STARTING_ARMOR 2
#define RIFLEMAN_STARTING_ARMOR 1
#define SPECOPS_STARTING_ARMOR 1
#define PARATROOPER_STARTING_ARMOR 1
#define ENGINEER_STARTING_ARMOR 1
#define SCOUT_STARTING_ARMOR 1
#define SEARCHLIGHT_STARTING_ARMOR 1

const u8 startingArmor[NUM_PIECE_TYPES] =
{
	KING_STARTING_ARMOR,
	GUARD_STARTING_ARMOR,
	RIFLEMAN_STARTING_ARMOR,
	SPECOPS_STARTING_ARMOR,
	PARATROOPER_STARTING_ARMOR,
	ENGINEER_STARTING_ARMOR,
	SCOUT_STARTING_ARMOR,
	SEARCHLIGHT_STARTING_ARMOR,
};

#define KING_VISION 5
#define GUARD_VISION 2
#define RIFLEMAN_VISION 4
#define SPECOPS_VISION 3
#define ENGINEER_VISION 2
#define SCOUT_VISION 6
#define SEARCHLIGHT_VISION 5



#endif
